# Analysis for the counter-zero tests

### This is to deal with MWorks skipping counter zero after code changes in ngfriedman/2310/imaginggate-laseroff 

- files in data/241111-countertest-issue[123].mwk2
- testing mwkfiles.py reader code

### references
- see MH LabArchives notes

# Logic of changes

### Previously, in mwkfiles.py

- Find the last zero tick
- Find the first 1 tick
- Check (line 372, 1e076ce) that the stim level is set between the 0 and 1 tick. (This no longer happens)
- Check that no counter ticks are skipped or duplicated
- Some rough checks that we have the right number of ticks for the number of stimuli

### What changed in hardware

- In some cases on rig C2, when scanimage is started, resetting the MWorks counter variable sets the counter to 1 —-- the 1 tick happens in under 1ms after the 0 tick

### Now, plan for what to do:
- we detect this situation and subtract 1 from all counter values.
- key check: if first 1 (in 4th or 5th index spot) follows previous code by < 1ms, it means the zero code was missed, the first 1 is really zero, and the first 2 is really a 1. Fix by subtracting.


## TODO 250119:
- looks like the problem is in finding the start of the trial - with counter tick = 1 or something else. Let's figure out where the counter 1 happens and the first tick time and see if that needs correcting or can be used as the start of the trial, or if I have to find the start of the trial a different way
- Smaller h5 files for push

In [1]:
%autoreload 2

from pathlib import Path
import sys, os
from types import SimpleNamespace
import pandas as pd 

import mworksbehavior as mwb
from mworksbehavior import mwkfiles

## check to make sure the mwkfiles code is coming from the right place
# there may be better ways to do this, by forcing mwb directory to
# start of sys.path, for ex
packdir = Path('~/Repositories/mworksbehavior/mworksbehavior').expanduser()
# if this assertion fails you may need cd ~/Repositories/mworksbehavior; pip -e .
assert packdir.resolve() == Path(mwb.__path__[0]).resolve(), \
  'does not look like mworksbehavior is installed in editable form at ~/Repositories/mworksbehavior'

In [2]:
datdir = Path('~/Repositories/mworksbehavior/mworksbehavior/tests/data').expanduser()

#mwkname = f'240918-countertest-issue1.mwk2'
mwkname = f'240918-countertest-issue2.mwk2'
#mwkname = f'241111-countertest-issue3.mwk2'

### Read the file using the plain MWF code and display the codestream for debugging

In [3]:
# Read the file using the plain MWF code
fulln = datdir / mwkname

mwf = mwkfiles.MWKFile(fulln);

In [4]:
print(mwf.firstTrStartTimeUs)
print(mwf.lastTrEndTimeUs)

262011259
330127328

In [5]:
counterIx = mwf.df.tagname.isin(['stimPySelLevel'])
mwf.df.loc[counterIx,:]

             tagname     timeUs value  timeFmStUs
159   stimPySelLevel  260282108     2         129
363   stimPySelLevel  260284031     2        2052
574   stimPySelLevel  262000699     2     1718720
693   stimPySelLevel  262016905     2     1734926
1922  stimPySelLevel  274133434     5    13851455
2905  stimPySelLevel  282133522     6    21851543
3888  stimPySelLevel  290134206     7    29852227
4871  stimPySelLevel  298133377     0    37851398
5866  stimPySelLevel  306133609     4    45851630
6849  stimPySelLevel  314133860     3    53851881
7844  stimPySelLevel  322133809     1    61851830
8839  stimPySelLevel  330133545     6    69851566

In [6]:
## quick counterFIO analysis from raw stream
counterIx = mwf.df.tagname.isin(['counterFIO'])
cdf = mwf.df.loc[counterIx,:]
np.unique(np.diff(cdf.value))

array([-2244, 0, 1], dtype=object)

In [7]:
counterIx = mwf.df.tagname.isin(['counterFIO','strobedDigitalWord', 'stimPySelLevel'])
pd.set_option('display.max_rows', 60)
pd.set_option('display.min_rows', 50)


mwf.df.loc[counterIx,:]

                 tagname     timeUs value  timeFmStUs
159       stimPySelLevel  260282108     2         129
197   strobedDigitalWord  260282124     4         145
199           counterFIO  260282124  2245         145
363       stimPySelLevel  260284031     2        2052
401           counterFIO  260284135  2245        2156
402   strobedDigitalWord  260284136     4        2157
574       stimPySelLevel  262000699     2     1718720
612           counterFIO  262000750  2245     1718771
613   strobedDigitalWord  262000750     4     1718771
637   strobedDigitalWord  262009570     0     1727591
649   strobedDigitalWord  262011259   170     1729280
650           counterFIO  262011346     1     1729367
652   strobedDigitalWord  262011799   170     1729820
654   strobedDigitalWord  262012280   170     1730301
659   strobedDigitalWord  262012753   200     1730774
661   strobedDigitalWord  262013199     0     1731220
663   strobedDigitalWord  262013639     0     1731660
665   strobedDigitalWord  262014109   262     1732130
667   strobedDigitalWord  262014584    12     1732605
669   strobedDigitalWord  262015064   201     1733085
691   strobedDigitalWord  262016140     6     1734161
693       stimPySelLevel  262016905     2     1734926
1040          counterFIO  266196329     2     5914350
1043          counterFIO  266226330     3     5944351
1046          counterFIO  266261316     4     5979337
...                  ...        ...   ...         ...
8726          counterFIO  329826414  1911    69544435
8729          counterFIO  329861334  1912    69579355
8732          counterFIO  329896328  1913    69614349
8735          counterFIO  329926334  1914    69644355
8738          counterFIO  329961313  1915    69679334
8741          counterFIO  329996317  1916    69714338
8744          counterFIO  330026332  1917    69744353
8747          counterFIO  330061329  1918    69779350
8750          counterFIO  330096412  1919    69814433
8753          counterFIO  330126320  1920    69844341
8775  strobedDigitalWord  330126400    85    69844421
8777  strobedDigitalWord  330126883    85    69844904
8779  strobedDigitalWord  330127328    85    69845349
8794  strobedDigitalWord  330127834   170    69845855
8797  strobedDigitalWord  330128279   170    69846300
8799  strobedDigitalWord  330128743   170    69846764
8804  strobedDigitalWord  330129224   200    69847245
8806  strobedDigitalWord  330129766     0    69847787
8809  strobedDigitalWord  330130274     0    69848295
8811  strobedDigitalWord  330130730   330    69848751
8813  strobedDigitalWord  330131201   129    69849222
8815  strobedDigitalWord  330131926   201    69849947
8837  strobedDigitalWord  330132938     6    69850959
8839      stimPySelLevel  330133545     6    69851566
8937          counterFIO  330161478  1921    69879499

[2081 rows x 4 columns]

### Test with the full mwkfiles.RetinotopyMap2Stim / CounterStimMixin parsing code

In [8]:
mwf = mwkfiles.RetinotopyMap2StimMWKFile(fulln,doTryFixCorrupt=True)
mwf.compute_imaging_constants()
print(mwf.nstim, mwf.nframes_stim)
assert mwf.nstim * mwf.nframes_stim == 1920

262016795
1919 12 159.91666666666666
8 240

/Users/histed/Repositories/mworksbehavior/mworksbehavior/mwkfiles.py:374: UserWarning: Found first counter tick to be 1, expected zero; subtracting 1 from all counter vals, altering df values
  warnings.warn(f"Found first counter tick to be 1, expected zero; subtracting 1 from all counter vals, altering df values")
/Users/histed/Repositories/mworksbehavior/mworksbehavior/mwkfiles.py:474: UserWarning: Trying to fix file: Number of frames is one less than expected, probably first trial is short, be careful w/ analysis
  warnings.warn('Trying to fix file: Number of frames is one less than expected, probably first trial is short, be careful w/ analysis')

In [14]:
display(mwf.counterStats)

namespace(nCounterTicks=1919, nTotalStims=12)

In [9]:
display(mwf.firstCounterUs)
display(mwf.firstTrStartTimeUs)
display(mwf.firstTrEndTimeUs)
display(mwf.constS)

tdf = mwf.get_codedf(mwf.counterVar)
display(tdf)

display(mwf.stimDf)

counterStatN = SimpleNamespace(minCounterVal=min(tdf.value),
                               maxCounterVal=max(tdf.value), 
                               nTotalStim=len(mwf.stimDf),
                               nUniqueStim=mwf.nstim)
ctSN = counterStatN
ctSN.counterRange = ctSN.maxCounterVal - ctSN.minCounterVal + 2 # count at both ends
ctSN.counterTickPerStim = ctSN.counterRange/ctSN.nTotalStim
display(ctSN)

0    266196329
Name: timeUs, dtype: int64

262011259

274126555

counterNPre      60
counterNPost    120
counterNStim     60
dtype: int64

      df_index     timeUs value  timeFmStUs  timeDiffUs
0         1040  266196329     1     5914350         NaN
1         1043  266226330     2     5944351     30001.0
2         1046  266261316     3     5979337     34986.0
3         1049  266296318     4     6014339     35002.0
4         1052  266326325     5     6044346     30007.0
5         1055  266361309     6     6079330     34984.0
6         1058  266396339     7     6114360     35030.0
7         1061  266426328     8     6144349     29989.0
8         1064  266461314     9     6179335     34986.0
9         1067  266496332    10     6214353     35018.0
10        1070  266526341    11     6244362     30009.0
11        1073  266561406    12     6279427     35065.0
12        1076  266596335    13     6314356     34929.0
13        1079  266626373    14     6344394     30038.0
14        1082  266661331    15     6379352     34958.0
15        1085  266696341    16     6414362     35010.0
16        1088  266726312    17     6444333     29971.0
17        1091  266761372    18     6479393     35060.0
18        1094  266796341    19     6514362     34969.0
19        1097  266826332    20     6544353     29991.0
20        1100  266861467    21     6579488     35135.0
21        1103  266896392    22     6614413     34925.0
22        1106  266926337    23     6644358     29945.0
23        1109  266961318    24     6679339     34981.0
24        1112  266996342    25     6714363     35024.0
...        ...        ...   ...         ...         ...
1894      8681  329326315  1895    69044336     29961.0
1895      8684  329361528  1896    69079549     35213.0
1896      8687  329396315  1897    69114336     34787.0
1897      8690  329426326  1898    69144347     30011.0
1898      8693  329461315  1899    69179336     34989.0
1899      8696  329496353  1900    69214374     35038.0
1900      8699  329526319  1901    69244340     29966.0
1901      8702  329561373  1902    69279394     35054.0
1902      8705  329596327  1903    69314348     34954.0
1903      8708  329626358  1904    69344379     30031.0
1904      8711  329661332  1905    69379353     34974.0
1905      8714  329696346  1906    69414367     35014.0
1906      8717  329726326  1907    69444347     29980.0
1907      8720  329761314  1908    69479335     34988.0
1908      8723  329796327  1909    69514348     35013.0
1909      8726  329826414  1910    69544435     30087.0
1910      8729  329861334  1911    69579355     34920.0
1911      8732  329896328  1912    69614349     34994.0
1912      8735  329926334  1913    69644355     30006.0
1913      8738  329961313  1914    69679334     34979.0
1914      8741  329996317  1915    69714338     35004.0
1915      8744  330026332  1916    69744353     30015.0
1916      8747  330061329  1917    69779350     34997.0
1917      8750  330096412  1918    69814433     35083.0
1918      8753  330126320  1919    69844341     29908.0

[1919 rows x 5 columns]

,stimPySelLevel,tStim1AzimuthDeg,tStim2AzimuthDeg,tStim1ElevationDeg,tStim2ElevationDeg,tStim1GratingSpeedDps,tStim2GratingSpeedDps,tStim1GratingSpatialFreqCpd,tStim2GratingSpatialFreqCpd,tStim1OriNoiseF0Cpd,...,tATrainNPulses,tBTrainNPulses,tATrainPulseLengthMs,tBTrainPulseLengthMs,tARampLengthMs,tBRampLengthMs,tARampExtraConstantLengthMs,tBRampExtraConstantLengthMs,tAStartOffsetMs,tBStartOffsetMs
0,2,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
1,5,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
2,6,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
3,7,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
4,0,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
5,4,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
6,3,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0
7,1,0,0,0,0,20,0,0.1,0.1,0.1,...,2,2,10,100,2,2,0,0,0,0

namespace(minCounterVal=1,
          maxCounterVal=1919,
          nTotalStim=8,
          nUniqueStim=8,
          counterRange=1920,
          counterTickPerStim=240.0)

In [10]:
1920/mwf.nframes_stim

8.0

In [11]:
#dir(mwf)
mwf.df.loc[0:10, :]

,tagname,timeUs,value,timeFmStUs
0,#allowAltFailover,260281979,0,0
1,#state_system_mode,260281995,0,16
2,#announceMessage,260281998,0,19
3,#stimDisplayUpdate,260282007,[],28
4,#stimDisplayCapture,260282008,,29
5,#experimentLoadProgress,260282009,1.0,30
6,#loadedExperiment,260282009,{'/Users/holdanddetect/Repositories/Experiment...,30
7,#announceSound,260282020,"{'action': 'play', 'filename': '/var/folders/8...",41
8,#announceCalibrator,260282022,{},43
9,#requestCalibrator,260282023,{},44
10,#announceCurrentState,260282023,814,44

In [12]:
counterIx = mwf.df.tagname.isin(['counterFIO','strobedDigitalWord', 'stimPySelLevel'])
pd.set_option('display.max_rows', 50)
pd.set_option('display.min_rows', 40)


mwf.df.loc[counterIx,:]

                 tagname     timeUs value  timeFmStUs
159       stimPySelLevel  260282108     2         129
197   strobedDigitalWord  260282124     4         145
199           counterFIO  260282124  2245         145
363       stimPySelLevel  260284031     2        2052
401           counterFIO  260284135  2245        2156
402   strobedDigitalWord  260284136     4        2157
574       stimPySelLevel  262000699     2     1718720
612           counterFIO  262000750  2245     1718771
613   strobedDigitalWord  262000750     4     1718771
637   strobedDigitalWord  262009570     0     1727591
649   strobedDigitalWord  262011259   170     1729280
652   strobedDigitalWord  262011799   170     1729820
654   strobedDigitalWord  262012280   170     1730301
659   strobedDigitalWord  262012753   200     1730774
661   strobedDigitalWord  262013199     0     1731220
663   strobedDigitalWord  262013639     0     1731660
665   strobedDigitalWord  262014109   262     1732130
667   strobedDigitalWord  262014584    12     1732605
669   strobedDigitalWord  262015064   201     1733085
691   strobedDigitalWord  262016140     6     1734161
...                  ...        ...   ...         ...
8741          counterFIO  329996317  1915    69714338
8744          counterFIO  330026332  1916    69744353
8747          counterFIO  330061329  1917    69779350
8750          counterFIO  330096412  1918    69814433
8753          counterFIO  330126320  1919    69844341
8775  strobedDigitalWord  330126400    85    69844421
8777  strobedDigitalWord  330126883    85    69844904
8779  strobedDigitalWord  330127328    85    69845349
8794  strobedDigitalWord  330127834   170    69845855
8797  strobedDigitalWord  330128279   170    69846300
8799  strobedDigitalWord  330128743   170    69846764
8804  strobedDigitalWord  330129224   200    69847245
8806  strobedDigitalWord  330129766     0    69847787
8809  strobedDigitalWord  330130274     0    69848295
8811  strobedDigitalWord  330130730   330    69848751
8813  strobedDigitalWord  330131201   129    69849222
8815  strobedDigitalWord  330131926   201    69849947
8837  strobedDigitalWord  330132938     6    69850959
8839      stimPySelLevel  330133545     6    69851566
8937          counterFIO  330161478  1920    69879499

[2080 rows x 4 columns]

In [13]:
mwf.df.loc[(mwf.df.tagname=='stimPySelLevel'),:]

             tagname     timeUs value  timeFmStUs
159   stimPySelLevel  260282108     2         129
363   stimPySelLevel  260284031     2        2052
574   stimPySelLevel  262000699     2     1718720
693   stimPySelLevel  262016905     2     1734926
1922  stimPySelLevel  274133434     5    13851455
2905  stimPySelLevel  282133522     6    21851543
3888  stimPySelLevel  290134206     7    29852227
4871  stimPySelLevel  298133377     0    37851398
5866  stimPySelLevel  306133609     4    45851630
6849  stimPySelLevel  314133860     3    53851881
7844  stimPySelLevel  322133809     1    61851830
8839  stimPySelLevel  330133545     6    69851566